server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ouo_course?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: rootroot
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 86400  # 保存时间为24h
  jackson:
    time-zone: Asia/Shanghai
  data:
    mongodb:
      uri: mongodb://localhost:27017/ouo_course

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: run.ouo.app.model